* Booru One Click Downloder
A WebExtension to download image with comprehensible filename from Booru page in one click.

Currently supported sites:

- SankakuComplex
- Yande.re
- Konachan.com
- Konachan.net

For more information please see [[https://github.com/kuanyui/BooruDownloader][GitHub]].

* Install
- [[][Mozilla Add-ons]]

* Screenshot
[[]]

* Supported Browser
- Firefox for Desktop >= 61
- Firefox for Android >= 61

* Requirements for Development
- Node
- web-ext
- GNU Make
- Python 3 (For HTTP server)

* Development
** Prepare
#+BEGIN_SRC sh
npm i
#+END_SRC

** Run for development (Watch)
#+BEGIN_SRC sh
make dev
web-ext run --verbose --firefox-profile ~/.mozilla/firefox/PROFILE_DIR_NAME
#+END_SRC
#+BEGIN_QUOTE
If webpack watch exit immediately without any error, please try [[https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers]]
#+END_QUOTE

** Run Firefox for developing WebExtension
#+BEGIN_SRC sh
web-ext run --verbose --firefox-profile ~/.mozilla/firefox/XXXXXXX.NAME
#+END_SRC

** Deploy (Build .xpi file & run a HTTP server for download)
#+BEGIN_SRC sh
make xpi-server
#+END_SRC

** Zip this repository for uploading to addons.mozilla.org
#+BEGIN_SRC sh
make zip-repo
#+END_SRC

* Permission
For paranoid users such as me, these are all used permissions with its usages:

- =downloads=:
  - Download.

- =tabs=:
  - Detect if currently is in supported site, to decide to show/hide =pageAction=. (It's impossible to achive this via only =manifest.json= on Firefox for Android)

- =storage=:
  - (Not Implemented Yet) For saving user preferences in your Mozilla account (=storage.sync=)

- =konachan.net=, ...
  - Insert script & CSS to grab tags, grab image's link, insert HTML & CSS to show dowbload buttons.

* TODOs
- Customizable keyboard shortcuts.
- Maybe always show buttons, without =pageAction=?.
* License
WTFPL 2.0